### ISSUE TITLE
[kfence] Test with aggressive test config

### ISSUE THREAD

**Issue by melver** [google/kasan#108]
Test with the following config. It enables various debugging tools, and enables KFENCE + fault-injection (due to fault-injection, ignore all KFENCE reports).

Currently this config is unable to boot the kernel. Disabling KFENCE results in a bootable kernel again.

There are various issues:
- kmemleak complains
- lockdep complains
- panics eventually

Also try things like (if able to boot):
```
$> echo function > /sys/kernel/debug/tracing/current_tracer
```

[config-kfence.txt](https://github.com/google/kasan/files/4984086/config-kfence.txt)

**Comment by ramosian-glider** [comment]
With `kfence.sample_rate=0` the following report still reproduces:

```
[    4.008908][    T1] x86/mm: Checking user space page tables^M
[    4.009643][    T1] ------------[ cut here ]------------^M
[    4.010218][    T1] x86/mm: Found insecure W+X mapping at address startup_64+0x0/0x30^M
```
(i.e. is unrelated to KFENCE)

**Comment by melver** [comment]
> With `kfence.sample_rate=0` the following report still reproduces:
> 
> ```
> [    4.008908][    T1] x86/mm: Checking user space page tables^M
> [    4.009643][    T1] ------------[ cut here ]------------^M
> [    4.010218][    T1] x86/mm: Found insecure W+X mapping at address startup_64+0x0/0x30^M
> ```
> 
> (i.e. is unrelated to KFENCE)

Ok good, let's see if this one's fixed in newer kernels, although the remaining ones are probably real then. Getting it to boot would be the first step, and then trying to get all the other issues, including kmemleak, to work would be good.

**Comment by melver** [comment]
I think all issues have been fixed now. We can leave it open to continue including this config in tests.
