### ISSUE TITLE
[kfence] Documentation (incl. API docs, Documentation, commit messages, wiki)

### ISSUE THREAD

**Issue by melver** [google/kasan#120]
Need to write all sorts of documentation:

- [x] In-code API docs;
- [x] Documentation/dev-tools/kfence.rst;
- [x] Commit messages;
- [x] Cover letter (probably can be almost identical to first commit message).
- [x] Wiki entry that we can can use to point to project;

Once we have that, we're almost good for RFC.

**Comment by melver** [comment]
Updated commit messages.

The work-in-progress version of the rebase and commit messages is here: https://github.com/google/kasan/commits/kfence-rebased-tmp -- we can update the `kfence` branch from it before RFC. `git diff kfence-rebased-tmp..kfence` should yield no diff!

**Comment by ramosian-glider** [comment]
Added https://github.com/google/kasan/blob/master/KFENCE.md as a replacement for a Wiki page.
