### ISSUE TITLE
jump_labels, kfence: Avoid IPIs on toggling static branch

### ISSUE THREAD

**Issue by melver** [google/kasan#167]
With ever increase core counts in modern CPUs, it would be wise to avoid triggering 2 IPIs due to static branch enable+disable for each KFENCE allocation.

Investigate making changes to the static_keys/jump_labels infrastructure, that would allow us to avoid the 2 IPIs we currently require. More details are already in a comment in the KFENCE code: https://github.com/google/kasan/blob/kfence/mm/kfence/core.c#L575

**Comment by xairy** [comment]
Should we move this to [Bugzilla](https://bugzilla.kernel.org/buglist.cgi?component=Sanitizers&list_id=1103883&product=Memory%20Management&resolution=---)?

**Comment by melver** [comment]
Hmm, no, I consider this fixed by: https://lore.kernel.org/all/20211019102524.2807208-2-elver@google.com/

**Comment by xairy** [comment]
Let's close this then. Thanks!
