### ISSUE TITLE
kasan_slab_free can corrupt shadow and object header

### ISSUE THREAD

**Issue by dvyukov** [google/kasan#38]
``` c
bool kasan_slab_free(struct kmem_cache *cache, void *object)
{
        switch (alloc_info->state) {
        case KASAN_STATE_ALLOC:
            alloc_info->state = KASAN_STATE_QUARANTINE;
            quarantine_put(free_info, cache);
            set_track(&free_info->track, GFP_NOWAIT);
            kasan_poison_slab_free(cache, object);
            return true;
```

We first put the object into quarantine and then poison shadow and update header. The object can be pushed out of the quarantine and reused before we update shadow/header. As the result shadow and header will be corrupted.
We need to update shadow/header before making the object available for reuse.

**Comment by xairy** [comment]
This looks fixed in mainline KASAN.
