### ISSUE TITLE
unified header for reports

### ISSUE THREAD

**Issue by dvyukov** [google/kasan#40]
For one set of reports we print:

```
BUG: KASAN: slab-out-of-bounds in memcpy+0x1d/0x40 at addr ffff88003a6bd110
Read of size 8 by task a.out/6260
```

for another:

```
BUG: KASAN: null-ptr-deref on address           (null)
Read of size 4 by task syz-executor/22534
```

This complicates parsing, and the the second case we don't have a function name which complicates unique identification of bugs: null-ptr-deref is too vague, two such bugs may or may not be the same.

We should always print the first form:

```
KASAN: {TYPE} in {FUNC} at addr {ADDR}
(Read|Write) of size {SIZE} by task
```

**Comment by xairy** [comment]
Fixed by https://github.com/torvalds/linux/commit/7d418f7b0d3407b93ec70f3b380cc5beafa1fa68
