### ISSUE TITLE
[kfence] Support ARM64

### ISSUE THREAD

**Issue by ramosian-glider** [google/kasan#47]
Most of the code is arch-agnostic, but page protection may need to be ported to ARM64

**Comment by melver** [comment]
We have a prototype (https://github.com/google/kasan/pull/123), but we should still try to figure out how to make it work with the static pool.

**Comment by melver** [comment]
Since the last comment here, we have a version using alloc_pages(). We've been trying to get a static-pool.

FTR; With input from Mark, Alex provides some more insights into static pool for arm64: https://lkml.kernel.org/r/CAG_fn=VOR-3LgmLY-T2Fy6K_VYFgCHK0Hv+Y-atrvrVZ4mQE=Q@mail.gmail.com

**Comment by melver** [comment]
We abandoned the static pool entirely, and the current arm64 version won't receive major changes.
