### ISSUE TITLE
[kfence] Stolen freelists are CPU-local

### ISSUE THREAD

**Issue by ramosian-glider** [google/kasan#62]
SLUB uses per-CPU freelists on allocation fast path, so we need to ensure we steal evenly from each CPU.
`kfence_steal_freelist()` always steals the freelist from the current CPU, and `kfence_fix_freelist()`fixes it for the current CPU, even if the freelist was stolen from another CPU.
We may want to do one of the following:

- steal every `cache->cpu_slab->freelist` for the cache in `kfence_steal_freelist()`. In that case every allocation from that cache on every other CPU will be waiting for `kfence_alloc_and_fix_freelist()` to finish and restore the freelists.
- pick a random CPU in `kfence_steal_freelist()` and steal only the corresponding freelist.

**Comment by melver** [comment]
I think the fairest result will be obtained by picking a random CPU. Fair as in on every system, regardless of number of CPUs, adjusting the sample rate has a predictable result on system behaviour without having to think about number of CPUs and factoring that into what the sample rate should be.

**Comment by ramosian-glider** [comment]
Should be fine now.
