### ISSUE TITLE
[kfence] Reconsider using stack depot

### ISSUE THREAD

**Issue by ramosian-glider** [google/kasan#66]
It is nice that we don't have to invent our own storage for stack traces, but stackdepot may increase our memory footprint, as it does not garbage collect stacks.

It is actually enough to allocate `KFENCE_STACK_DEPTH * 8 bytes * 2 for alloc/free stacks * 256 objects` bytes once and overwrite old stacks as objects get reused.

**Comment by dvyukov** [comment]
I agree, I think we should not use stack depot for KFENCE.
