### ISSUE TITLE
[kfence] Avoid intermediate string buffers for dumping information

### ISSUE THREAD

**Issue by melver** [google/kasan#69]
Avoid intermediate string buffers for dumping information to console or debugfs.

**Comment by ramosian-glider** [comment]
More context here: https://github.com/google/kasan/pull/68, but it's still unclear to me which intermediate buffers you were talking about. Those we allocate with alloc_pages()?

**Comment by melver** [comment]
> More context here: #68, but it's still unclear to me which intermediate buffers you were talking about. Those we allocate with alloc_pages()?

Yes, we should just be able to directly seq_printf or pr_ the contents. It may require passing a function pointer but because pr_ are macros and printk doesn't take the same args as seq_printf, it may require some other trickery to make the function more generic.

**Comment by ramosian-glider** [comment]
On a second thought, I think we'd better not call printk() in the reporting code, as it may allocate memory, which can lead to deadlocks.
We can perhaps pre-allocate the needed buffers instead of calling aloc_pages() every time we need to print an object.

**Comment by ramosian-glider** [comment]
Guess we can close this for now. One global buffer protected by a lock is enough so far.

**Comment by melver** [comment]
We still have an intermediate buffer, but as you say, if we can't call printk() immediately then the global buffer is probably as good as we can make it.

**Comment by ramosian-glider** [comment]
Marco, guess you've fixed the remnants in 95de3b56f7e1cfc38e45094cb296d20320d8d8f7 ?

**Comment by melver** [comment]
> Marco, guess you've fixed the remnants in [95de3b5](https://github.com/google/kasan/commit/95de3b56f7e1cfc38e45094cb296d20320d8d8f7) ?

Yes, this can be closed.
